image: docker:stable

variables:
  IMAGE_TAG_TEST: $CI_REGISTRY_IMAGE/tmp:b$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest

stages:
  - building
  - testing
  - release

.docker: &docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  only:
    - /^\d+\.\d+\.\d+$/

build_service:
  <<: *docker
  stage: building
  script:
    # - docker image build --build-arg RELEASE_TAG="${CI_COMMIT_TAG}" --build-arg SSH_PRIVATE_KEY="${SSH_PRIVATE_KEY}" -t $IMAGE_TAG_TEST .
    - docker build -t $IMAGE_TAG_TEST .
    - docker push $IMAGE_TAG_TEST

test_service:
  <<: *docker
  stage: testing
  script:
    # - docker pull $IMAGE_TAG_TEST
    - exit 0

release:
  <<: *docker
  stage: release
  script:
    - docker pull $IMAGE_TAG_TEST
    - docker tag $IMAGE_TAG_TEST $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $IMAGE_TAG_TEST $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG_LATEST

